[package]
name = "agenda"
description = "A command-line tool to see the days events."
version = "0.1.0"
edition = "2024"
homepage = "https://github.com/ptsouchlos/agenda"
repository = "https://github.com/ptsouchlos/agenda"
license = "MIT"
topics = ["calendar", "events", "cli", "productivity"]

[[bin]]
name = "agenda"
path = "src/main.rs"

[build-dependencies]
shadow-rs = "1.7.1"

[dependencies]
shadow-rs = "1.7.1"
clap = { version = "4", features = ["derive"] }
ureq = { version = "2", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1.1.2"
handlebars = "6"
indicatif = "0.18"
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
dirs = "6"
iso8601-duration = "0.2"
chrono-tz = "0.10"
